apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.2
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-3.5.2.jar
  sparkVersion: 3.5.2
  driver:
    javaOptions: "-Ddd.data.jobs.enabled=true -Ddd.service=spark-pi -Ddd.env=gian-lab -Ddd.version=1.0 -Ddd.tags=clustername:gian,teste:gian -Ddd.logs.injection=true"
    annotations:
      ad.datadoghq.com/spark-kubernetes-driver.check_names: '["spark"]'
      ad.datadoghq.com/spark-kubernetes-driver.init_configs: '[{}]'
      ad.datadoghq.com/spark-kubernetes-driver.instances: '[{"spark_url": "http://%%host%%:4040", "spark_cluster_mode": "spark_driver_mode", "cluster_name": "spark-k8s"}]'
      admission.datadoghq.com/java-lib.version: "latest"
    labels:
      admission.datadoghq.com/enabled: "true"
      version: 3.5.2
    cores: 1
    coreLimit: 1200m
    memory: 512m
    serviceAccount: spark
  executor:
    javaOptions: "-Ddd.data.jobs.enabled=true -Ddd.service=spark-pi -Ddd.env=gian-lab -Ddd.version=1.0 -Ddd.tags=clustername:gian,teste:gian -Ddd.logs.injection=true"
    annotations:
      admission.datadoghq.com/java-lib.version: "latest"
    labels:
      admission.datadoghq.com/enabled: "true"
      version: 3.5.2
    instances: 1
    cores: 1
    coreLimit: 1200m
    memory: 512m